### ISSUE TITLE
关于 `PyExecJS` 依赖包停止维护请求升级依赖或替换依赖

### ISSUE THREAD

**Issue by taotieren** [Moxin1044/qsnctf-python#1]
关于 `PyExecJS` 依赖包停止维护请求升级依赖或替换依赖

- https://pypi.org/project/PyExecJS/

> PyExecJS (EOL)
> End of life
>This library is no longer maintananced. Bugs are not be fixed (even if they are trivial or essential).
> 
> We suggest to use other library or to make a fork.

PyExecJS2 替换包

- https://pypi.org/project/PyExecJS2/

或者升级成其他依赖包

**Comment by Moxin1044** [comment]
您好，已在[0.0.8.10](https://github.com/Moxin1044/qsnctf-python/releases/tag/0.0.8.10)版本对该问题做出修复。
